site_name: Python Tools

theme:
  name: material

plugins:
  - mkdocstrings

markdown_extensions:
  - admonition
  - pymdownx.extra
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

watch:
  - Utils
  - TkUtils

nav:
  - Home: index.md
  - Utils:
    - Timer Context Manager: Utils/Timer.md
  - TkUtils:
    - Custom Tk Dialogs: TkUtils/dialogs.md
